### ISSUE TITLE
How to implement Vortice.Direct3D.Include in 1.9.77+

### ISSUE THREAD

**Issue by roy-t** [amerkoleci/Vortice.Windows#151]
Hello :),

I've been using v1.9.65 of Vortice.D3DCompiler/VorticeDirect3D11 to compile shaders like this
```
var include = new ShaderFileInclude(Path.GetDirectoryName(this.FullPath)); 
Compiler.Compile(sourceText, Defines, include, this.VertexShaderEntryPoint, this.FileName, this.VertexShaderProfile, out this.vertexShaderBlob, out var vsErrorBlob);
```

The class ShaderFileInclude looks like this:
```
    internal sealed class ShaderFileInclude : Vortice.Direct3D.Include
    {
        private readonly string RootFolder;
        public ShaderFileInclude(string rootFolder)
        {
            this.RootFolder = rootFolder;
        }

        public ShadowContainer Shadow { get; set; } // never set, property is null!

        public void Close(Stream stream) => stream.Close();

        public Stream Open(IncludeType type, string fileName, Stream parentStream)
        {
            switch (type)
            {
                case IncludeType.Local:
                    return File.OpenRead(Path.Combine(this.RootFolder, fileName));
                case IncludeType.System:
                default:
                    return File.OpenRead(fileName);
            }
        }

        public void Dispose() { }
    }
```

This worked great. However when upgrading to a newer version (1.9.77 or higher). This leads to a `System.NullReferenceException`, I think because I haven't initialized the `ShadowContainer Shadow` property. To be honest I don't really know what to do with it. I've looked through the source code in this repository. But I can't really figure out how to implement the `Vortice.Direct3D.Include` correctly or more specifically how to initialize the Shadow property.

Any hints?

**Comment by amerkoleci** [comment]
Hi,
You need to derive from CallbackBase as well.

Can you try that and see if it works? :)

**Comment by roy-t** [comment]
Wow that was fast.

I've tried deriving from `CallbackBase` but that leads to 

```
System.TypeInitializationException: 'The type initializer for 'Vortice.Direct3D.IncludeShadow' threw an exception.'
IndexOutOfRangeException: Index was outside the bounds of the array.

   at Vortice.Direct3D.IncludeShadow.get_Vtbl()
   at SharpGen.Runtime.CppObjectShadow.Initialize(ICallbackable callbackInstance)
   at SharpGen.Runtime.ShadowContainer.BuildGuidList(ICallbackable callbackable, IDictionary`2 guidToShadow)
   at SharpGen.Runtime.ShadowContainer..ctor(ICallbackable callbackable)
   at SharpGen.Runtime.CallbackBase.SharpGen.Runtime.ICallbackable.get_Shadow()
   at SharpGen.Runtime.MarshallingHelpers.ToCallbackPtr[TCallback](ICallbackable callback)
   at Vortice.D3DCompiler.Compiler.Compile(IntPtr srcDataRef, PointerSize srcDataSize, String sourceNameRef, ShaderMacro[] definesRef, Include includeRef, String entrypointRef, String targetRef, ShaderFlags flags1, EffectFlags flags2, Blob& codeOut, Blob& errorMsgsOut)
   at Vortice.D3DCompiler.Compiler.Compile(String shaderSource, ShaderMacro[] defines, Include include, String entryPoint, String sourceName, String profile, Blob& blob, Blob& errorBlob)
   at Mini.Engine.DirectX.Shader.Reload() in D:\Projects\C#\MiniEngine3\Mini.Engine.DirectX\Shader.cs:line 50
   at Mini.Engine.DirectX.Shader..ctor(ID3D11Device device, String fileName, String vertexShaderEntryPoint, String vertexShaderProfile, String pixelShaderEntryPoint, String pixelShaderProfile) in D:\Projects\C#\MiniEngine3\Mini.Engine.DirectX\Shader.cs:line 35
   at Mini.Engine.DirectX.Shader..ctor(ID3D11Device device, String fileName) in D:\Projects\C#\MiniEngine3\Mini.Engine.DirectX\Shader.cs:line 20
   at VorticeImGui.ImGuiRenderer..ctor(ID3D11Device device, ID3D11DeviceContext deviceContext) in D:\Projects\C#\MiniEngine3\Mini.Engine\Framework\ImGuiRenderer.cs:line 50
   at VorticeImGui.ImGuiPanel..ctor(RenderDoc renderDoc, Device device, IntPtr windowHandle, Int32 width, Int32 height) in D:\Projects\C#\MiniEngine3\Mini.Engine\Framework\ImGuiPanel.cs:line 25
   at VorticeImGui.Program.Main() in D:\Projects\C#\MiniEngine3\Mini.Engine\Program.cs:line 22
```

Just for reference my includer now looks like this

```
    internal sealed class ShaderFileInclude : CallbackBase, Include
    {
        private readonly string RootFolder;

        public ShaderFileInclude(string rootFolder)
        {
            this.RootFolder = rootFolder;
        }

        public void Close(Stream stream)
            => stream.Close();

        public Stream Open(IncludeType type, string fileName, Stream parentStream)
        {
            switch (type)
            {
                case IncludeType.Local:
                    return File.OpenRead(Path.Combine(this.RootFolder, fileName));
                case IncludeType.System:
                default:
                    return File.OpenRead(fileName);
            }
        }
    }
```

**Comment by andrew-boyarshin** [comment]
Confirmed regression in SharpGen _2.0.0-beta.9_. All `AddMethod(Delegate)` calls are broken. Fix for Vortice would be to use explicit `AddMethod(Delegate, uint)`, which is now recommended anyways.

**Comment by amerkoleci** [comment]
Any chance you can remove the broken method and submit PR please?

**Comment by roy-t** [comment]
Good morning, I've pulled the latest changes and I can confirm that they fix my issue! Thanks for the quick responses.

**Comment by amerkoleci** [comment]
Thanks for digging this issue, ping me if you have any other issues, will release new nuget package soon.
