### ISSUE TITLE
Error from SharpGen that has me preplexed. "The parameter is incorrect."

### ISSUE THREAD

**Issue by pyromanci** [amerkoleci/Vortice.Windows#192]
So I have program that was using SharpDX and decided to move to it Vortices. Since SharpDX started to throw an error that I couldn't seem to track down. So i removed the SharpDX nuget packages added added in the Vortice packages. So after reworking the screen capture code to use Vortice I was getting the same error. Now it's the `output1.DuplicateOutput(device);` line that is throwing the error. 

```
        private void InitDirectX()
        {
          using (var factory = DXGI.CreateDXGIFactory1<IDXGIFactory1>())
            {
                int adapters = 0;

                do
                {
                    using (var adapter = factory.GetAdapter(adapters)) 
                    { 
                        if (adapter == null) break;
                        adapters++;

                        int outputs = 0;

                        do
                        {
                            var output = adapter.GetOutput(outputs);
                            if (output == null) break;
                            outputs++;

                            var output1 = output.QueryInterface<IDXGIOutput1>();
                            var result = D3D11.D3D11CreateDevice(adapter, DriverType.Unknown, DeviceCreationFlags.None, _featureLevels, out var device);

                            if (result.Failure)
                            {
                                if (result.Code == Vortice.DXGI.ResultCode.WaitTimeout.Code)
                                {
                                    Logger.Write($"D3D11CreateDevice Timeout error.  Code: {result.Code}");
                                }
                                else
                                {
                                    Logger.Write($"D3D11CreateDevice error.  Code: {result.Code}");
                                }
                            }


                            var bounds = output1.Description.DesktopCoordinates;
                            var textureDesc = new Texture2DDescription
                            {
                                CpuAccessFlags = CpuAccessFlags.Read,
                                BindFlags = BindFlags.None,
                                Format = Format.B8G8R8A8_UNorm,
                                Width = bounds.Right - bounds.Left,
                                Height = bounds.Bottom - bounds.Top,
                                OptionFlags = ResourceOptionFlags.None,
                                MipLevels = 1,
                                ArraySize = 1,
                                SampleDescription = { Count = 1, Quality = 0 },
                                Usage = Vortice.Direct3D11.ResourceUsage.Staging
                            };

                            var duplication = output1.DuplicateOutput(device);
                            var currentFrame = device.CreateTexture2D(textureDesc);
                            var rotation = output1.Description.Rotation;
                            var devName = output1.Description.DeviceName;

                            _directxScreens.Add(devName, new DirectXOutput(adapter, device, duplication, currentFrame, rotation));

                        } while (true);
                    }
                } while (true);
            }
}
```

Now the application is a WPF app.  If I use the same code in say a console app I don't get the error and can generate a screen capture later on as needed. So this has me scratching my head. 

Here are the exact exception details
```
SharpGen.Runtime.SharpGenException
  HResult=0x80070057
  Message=HRESULT: [0x80070057], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The parameter is incorrect.

  Source=SharpGen.Runtime
  StackTrace:
   at SharpGen.Runtime.Result.ThrowFailureException()
   at SharpGen.Runtime.Result.CheckError()
   at Vortice.DXGI.IDXGIOutput1.DuplicateOutput(IUnknown deviceRef)
   at Remotely.Desktop.Win.Services.ScreenCapturerWin.InitDirectX() in Remotely\Desktop.Win\Services\ScreenCapturerWin.cs:line 327
```

**Comment by amerkoleci** [comment]
The issue is not related to vortice, probably WPF is creating d3d9/d3d11 device and you need to retrieve the IDXGIFactory from WPF, from msdn documentation :

The specified device (pDevice) is invalid, was not created on the correct adapter, or was not created from IDXGIFactory1 (or a later version of a DXGI factory interface that inherits from IDXGIFactory1).

**Comment by pyromanci** [comment]
Hrmm...  OK that has helped. I had to triple up on some debug out puts, but found that the InitDirectX() was in fact getting called multiple times. I need to do some more reading on the ServiceCollection. After adding extra to avoid dupluications. 

I'm now back at the my initial error that trigged me to do this switch in the first place. but now that this section has been cleaned up I can see where that crash is coming from cleaning now. Which doesn't have anything to do with DirectX. Well atleast the program is using a active library now.
