### ISSUE TITLE
D3DCompiler FileNotFoundException?

### ISSUE THREAD

**Issue by SuRGeoNix** [amerkoleci/Vortice.Windows#207]
Hi @amerkoleci, can you have a look at the below error and let me know if you have any clue what is going on.. Thanks!

```
---> System.IO.FileNotFoundException:
File name: 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

at Vortice.D3DCompiler.Compiler.Compile(IntPtr srcData, PointerSize srcDataSize, String sourceName, ShaderMacro[] defines, Include include, String entrypoint, String target, ShaderFlags flags1, EffectFlags flags2, Blob& code, Blob& errorMsgs)

at Vortice.D3DCompiler.Compiler.Compile(Byte[] shaderSource, ShaderMacro[] defines, Include include, String entryPoint, String sourceName, String profile, ShaderFlags shaderFlags, Blob& blob, Blob& errorBlob)

at FlyleafLib.MediaFramework.MediaRenderer.Renderer..ctor(VideoDecoder videoDecoder, Config config, Control control, Int32 uniqueId)
```

Source Code:
```csharp
assembly = Assembly.GetExecutingAssembly();
using (Stream stream = assembly.GetManifestResourceStream(@"FlyleafLib.MediaFramework.MediaRenderer.Shaders.FlyleafVS.hlsl"))
{
	byte[] bytes = new byte[stream.Length];
	stream.Read(bytes, 0, bytes.Length);
	Compiler.Compile(bytes, null, null, "main", null, $"vs{profileExt}", ShaderFlags.OptimizationLevel3, out vsBlob, out Blob vsError);
	if (vsError != null) Log(vsError.ConvertToString());
}
```

It doesn't happen on all systems... a user come up with this on Windows server 2012 R2

Just a thought, is it possible that this comes out because of a missing latest/updated Win or .NET 5.0 SDK on the target machine?

**Comment by SuRGeoNix** [comment]
Closing this one as it might occurred because of another issue. However, I am still interesting if you have any idea how it came up with that error.
