### ISSUE TITLE
System.InvalidCastException at IDxcLibrary.CreateIncludeHandler

### ISSUE THREAD

**Issue by Aminator** [amerkoleci/Vortice.Windows#28]
The second time I call `DxcCompiler.Compile` in my [DirectX12WinFormsApp](https://github.com/Aminator/DirectX12GameEngine/tree/master/DirectX12WinFormsApp) project it throws a `System.InvalidCastException`. I can't figure out why it only throws in this special case.

Here is the stack trace:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Error 0x2629.  Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30319.0&File=mscorrc.dll&Key=0x2629
  Source=System.Private.CoreLib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Vortice.Dxc.IDxcLibrary.CreateIncludeHandler()
   at Vortice.Dxc.DxcCompiler.Compile(DxcShaderStage shaderStage, String source, String entryPoint, String sourceName, DxcCompilerOptions options, DXCDefine[] defines, IDxcIncludeHandler include)
   at DirectX12GameEngine.Shaders.ShaderCompiler.Compile(DxcShaderStage shaderStage, String source, String entryPoint, String sourceName, DxcCompilerOptions options) in C:\Users\Amin\source\repos\Aminator\DirectX12GameEngine\DirectX12GameEngine.Shaders\ShaderCompiler.cs:line 25
```

**Comment by amerkoleci** [comment]
Probably you can create it only once or need to be released at least, currently I don't map it to IUknown and its not released
